package bg.keit.api.perforations.domain;
// Generated 05-Aug-2016 14:41:57 by Hibernate Tools 4.3.1.Final

/**
 * JobsId generated by hbm2java
 */
public class JobsId implements java.io.Serializable {

	private String machineId;
	private int jobId;

	public JobsId() {
	}

	public JobsId(String machineId, int jobId) {
		this.machineId = machineId;
		this.jobId = jobId;
	}

	public String getMachineId() {
		return this.machineId;
	}

	public void setMachineId(String machineId) {
		this.machineId = machineId;
	}

	public int getJobId() {
		return this.jobId;
	}

	public void setJobId(int jobId) {
		this.jobId = jobId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof JobsId))
			return false;
		JobsId castOther = (JobsId) other;

		return ((this.getMachineId() == castOther.getMachineId()) || (this.getMachineId() != null
				&& castOther.getMachineId() != null && this.getMachineId().equals(castOther.getMachineId())))
				&& (this.getJobId() == castOther.getJobId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getMachineId() == null ? 0 : this.getMachineId().hashCode());
		result = 37 * result + this.getJobId();
		return result;
	}

}
