package bg.keit.model.domain;
// Generated 05-Aug-2016 14:41:57 by Hibernate Tools 4.3.1.Final

import javax.persistence.Id;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Machines generated by hbm2java
 */

@Entity
@Table(name = "MACHINES")
public class Machines implements java.io.Serializable {

	@Id
	@Column(name="MACHINE_ID", length = 15)
	private String machineId;
	@Column(name="DESCRIBTION", length = 4000)
	private String describtion;
	//private Set<Perforations> perforationses = new HashSet<Perforations>(0);
	//private Set<Jobs> jobses = new HashSet<Jobs>(0);

	public Machines() {
	}

	public Machines(String machineId) {
		this.machineId = machineId;
	}

	public Machines(String machineId, String describtion/*, Set<Perforations> perforationses, Set<Jobs> jobses*/) {
		this.machineId = machineId;
		this.describtion = describtion;
		//this.perforationses = perforationses;
		//this.jobses = jobses;
	}

	public String getMachineId() {
		return this.machineId;
	}

	public void setMachineId(String machineId) {
		this.machineId = machineId;
	}

	public String getDescribtion() {
		return this.describtion;
	}

	public void setDescribtion(String describtion) {
		this.describtion = describtion;
	}

	/*public Set<Perforations> getPerforationses() {
		return this.perforationses;
	}

	public void setPerforationses(Set<Perforations> perforationses) {
		this.perforationses = perforationses;
	}

	public Set<Jobs> getJobses() {
		return this.jobses;
	}

	public void setJobses(Set<Jobs> jobses) {
		this.jobses = jobses;
	}*/



	@java.lang.Override
	public java.lang.String toString() {
		return "Machines{" +
				"machineId='" + machineId + '\'' +
				", describtion='" + describtion + '\'' +
				'}';
	}


}
