package bg.keit.model.domain;
// Generated 05-Aug-2016 14:41:57 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PerforationsId generated by hbm2java
 */
@Embeddable
public class PerforationsId implements java.io.Serializable {

	@Column(name = "MACHINE_ID", length = 15)
	private String machineId;
	@Column(name = "JOB_ID")
	private int jobId;
	@Column(name = "SERIAL_NUMBER")
	private int serialNumber;

	public PerforationsId() {
	}

	public PerforationsId(String machineId, int jobId, int serialNumber) {
		this.machineId = machineId;
		this.jobId = jobId;
		this.serialNumber = serialNumber;
	}

	public String getMachineId() {
		return this.machineId;
	}

	public void setMachineId(String machineId) {
		this.machineId = machineId;
	}

	public int getJobId() {
		return this.jobId;
	}

	public void setJobId(int jobId) {
		this.jobId = jobId;
	}

	public int getSerialNumber() {
		return this.serialNumber;
	}

	public void setSerialNumber(int serialNumber) {
		this.serialNumber = serialNumber;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PerforationsId))
			return false;
		PerforationsId castOther = (PerforationsId) other;

		return ((this.getMachineId() == castOther.getMachineId()) || (this.getMachineId() != null
				&& castOther.getMachineId() != null && this.getMachineId().equals(castOther.getMachineId())))
				&& (this.getJobId() == castOther.getJobId()) && (this.getSerialNumber() == castOther.getSerialNumber());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getMachineId() == null ? 0 : this.getMachineId().hashCode());
		result = 37 * result + this.getJobId();
		result = 37 * result + this.getSerialNumber();
		return result;
	}

}
