package bg.keit.model.domain;
// Generated 05-Aug-2016 14:41:57 by Hibernate Tools 4.3.1.Final

import javax.persistence.*;
import java.util.Date;

/**
 * Perforations generated by hbm2java
 */
public class Perforations implements java.io.Serializable {

	@EmbeddedId
	private PerforationsId id;
	@ManyToOne
	@JoinColumns({
			@JoinColumn(
					name = "MACHINE_ID", nullable = false,
					referencedColumnName = "MACHINE_ID"),
			@JoinColumn(
					name = "JOB_ID", nullable = false,
					referencedColumnName = "JOB_ID")
	})
	private Jobs jobs;
	@ManyToOne
	@JoinColumn(name="MACHINE_ID", nullable = false)
	private Machines machines;
	@Column(name = "ENCRYPTION_CODE", length = 4000)
	private String encryptionCode;
	@Column(name = "EXECUTION_DATE", length = 10)
	private Date executionDate;
	@Column(name = "EXECUTION_TIME", length = 8)
	private Date executionTime;
	@Column(name = "ECECUTION_USER", length = 4000)
	private String executionUser;
	@Column(name = "IMPORT_DATETIME", length = 19)
	private Date importDatetime;

	public Perforations() {
	}

	public Perforations(PerforationsId id, Jobs jobs, Machines machines) {
		this.id = id;
		this.jobs = jobs;
		this.machines = machines;
	}

	public Perforations(PerforationsId id, Jobs jobs, Machines machines, String encryptionCode, Date executionDate,
                        Date executionTime, String executionUser, Date importDatetime) {
		this.id = id;
		this.jobs = jobs;
		this.machines = machines;
		this.encryptionCode = encryptionCode;
		this.executionDate = executionDate;
		this.executionTime = executionTime;
		this.executionUser = executionUser;
		this.importDatetime = importDatetime;
	}

	public PerforationsId getId() {
		return this.id;
	}

	public void setId(PerforationsId id) {
		this.id = id;
	}

	public Jobs getJobs() {
		return this.jobs;
	}

	public void setJobs(Jobs jobs) {
		this.jobs = jobs;
	}

	public Machines getMachines() {
		return this.machines;
	}

	public void setMachines(Machines machines) {
		this.machines = machines;
	}

	public String getEncryptionCode() {
		return this.encryptionCode;
	}

	public void setEncryptionCode(String encryptionCode) {
		this.encryptionCode = encryptionCode;
	}

	public Date getExecutionDate() {
		return this.executionDate;
	}

	public void setExecutionDate(Date executionDate) {
		this.executionDate = executionDate;
	}

	public Date getExecutionTime() {
		return this.executionTime;
	}

	public void setExecutionTime(Date executionTime) {
		this.executionTime = executionTime;
	}

	public String getExecutionUser() {
		return this.executionUser;
	}

	public void setExecutionUser(String executionUser) {
		this.executionUser = executionUser;
	}

	public Date getImportDatetime() {
		return this.importDatetime;
	}

	public void setImportDatetime(Date importDatetime) {
		this.importDatetime = importDatetime;
	}
	
	public String getOCRNumber(){
		StringBuilder retOCR=new StringBuilder();//"";
		if (jobs.getMarkBatch()!=0) {
			retOCR.append(jobs.getBatchNumber().toString());
		}
		if (jobs.getMarkSn()!=0) {
			
			retOCR.append(jobs.getSnPrefix());
			retOCR.append(String.format("%0"+ Integer.toString(jobs.getSnLength()-jobs.getSnPrefix().length()-jobs.getSnSufix().length())+"d", id.getSerialNumber()));
			retOCR.append(jobs.getSnSufix());
			//+id.getSerialNumber()+jobs.getSnSufix();
		}
		return retOCR.toString();
	}

}
